# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master
- 202???
- 201???

trigger:
  batch: true
  branches:
    include:
    - master
    - 202???
    - 201???

# this part need to be set in UI
schedules:
- cron: "0 0 * * 6"
  displayName: Weekly build
  branches:
    include:
    - master
    - 202???
    - 201???
  always: true

resources:
  repositories:
  - repository: sonic-swss
    type: github
    name: vadymhlushko-mlnx/sonic-swss
    endpoint: vadymhlushko-mlnx

parameters:
  - name: debian_version
    type: string
    default: bullseye
variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      swss_common_artifact_name: sonic-swss-common
      artifact_name: sonic-sairedis
      syslog_artifact_name: sonic-sairedis.syslog
      run_unit_test: true
      archive_gcov: true
      debian_version: ${{ parameters.debian_version }}

- stage: BuildSwss
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-swss-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      artifact_name: sonic-swss
      debian_version: ${{ parameters.debian_version }}

- stage: BuildDocker
  dependsOn: BuildSwss
  condition: succeeded('BuildSwss')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: docker-sonic-vs

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log
